<?php
/**
 * @package CTEG
 * @subpackage VIEW
 */
?>
<div style="margin: 20px">
  <h1>CARGAR  UN ARCHIVO DE RESPALDO</H1>
  <P>PARA CARGAR UN ARCHIVO DE  RESPALDO SE DEBE PRESIONAR EN SELECCIONAR UN ARCHIVO LUEGO SELECCIONAS TU  ARCHIVO DE RESPALDO Y PRESIONAS EL BOTÓN GUARDAR UNA VEZ REALIZADA ESTA ACCIÓN  DEBERÁS ESPERAR DE 20 SEGUNDOS A VARIOS MINUTOS DEPENDIENDO DEL TAMAÑO DE TU  ARCHIVO DE RESPALDO</P>
  <P><IMG SRC="IMG/AYUDA/RESPALDO-1.JPG" WIDTH="507" HEIGHT="306"></P></P>
  <H2>POSIBLES  PROBLEMAS</H2>
  <P>SI LA CARGA SE TARDA DEMASIADO Y  LUEGO SE MUESTRA UN MENSAJE COMO ESTE </P>
  <H1><IMG SRC="IMG/AYUDA/CARGAR-RESPALDO-1.JPG" WIDTH="569" HEIGHT="59"></H1>
  <H1> </H1>
  <P>ES POR QUE PHP EXCEDIÓ EL LÍMITE  DE TIEMPO ESTO SE PUEDE RESOLVER ABRIENDO EL ARCHIVO PHP.INI DE PHP (POR FAVOR  CONSULTE LA DOCUMENTACIÓN DE PHP REFERENTE AL TEMA) Y EDITE LA DIRECTIVA MAX_EXECUTION_TIME</P>
  <H1><IMG SRC="IMG/AYUDA/CARGAR-RESPALDO-2.JPG" WIDTH="539" HEIGHT="163"></H1>
  <H1> </H1>
  <P>EL VALOR QUE DEBE TOMAR DEPENDERÁ  DEL TAMAÑO DEL ARCHIVO PERO POR LO GENERAL UN VALOR DE 600 ES MÁS QUE  SUFICIENTE GUARDE EL ARCHIVO Y LUEGO PROCEDA A RELANZAR EL SERVIDOR APACHE </P>
</DIV>