<?PHP
/**
 * @package CTEG
 * @subpackage VIEW
 */
?><?php

/* 
 * Here comes the text of your license  <?php define('__MYSQL_HOME_','C:\\\\xampp\\\\mysql\\\\bin');  define('USER','bd_teg'); define('PASS','KzUtGpSt08111K36'); define('HOST','localhost'); define('DB','bd_teg');define('__PROTOCOLO__','http');
 * Each line should be prefixed with  * 
 */
?>
<div style="margin: 20px;">

<h1 style="text-align: center;">CONFIGURACION INICIAL</h1>

<P style="text-align: justify;">
    PARA CONFIGURAR  C.T.E.G UNA VEZ INSTALADO SE DEBE ABRIR LA PAGINA DE &NegativeThickSpace;<A href="?page=install"> CONFIGURACION</a> <br>
ESTA SOLO ESTARA DISPONIBLE SI EL SISTEMA NO ESTA CORRECTAMENTE CONFIGURADO DONDE ENCOTRARAS LOS SIGUENTES FORMULARIOS 
<br><BR><BR>
<img src="img/ayuda/install.jpg" alt="" style="float: left;"/><BR><BR>
EL PRIMER CAMPO ES UNA CASILLA DE VERIFICACION SI LO SELECCIONAS EL SISTEMA<BR> SE EJECUTARA SOLO EN PROTOCOLO HTTPS SEGURO<BR><BR><BR>
EL SEGUNDO CAMPO (MYSQL) ES DE TEXTO,  ESTE CAMPO DEVE CONTENER LA DIRECCION DONDE SE ENCUENTRAN ALOJADOS LOS BINARIOS DE MYSQL<BR>
POR EJEMPLO SI ESTA USANDO UN SERVIDOR XAMPP EN WINDOWS EL DIRECTORIO SERIA <BR>C:\xampp\mysql\bin 
Y SI ES LINUX PODRIA SER /opt/lampp/bin
<br><br><br>
EL CAMPO NUMERO 3 (USUARIO MYSQL) DEBE INTRODUCIR EL NOMBRE DE USUARIO DEL SERVIDOR MYSQL QUE USARA, ESTE USUARIO PUEDE SER EL ROOT O <BR>
CUALQUIER OTRO USUARIO QUE TENGA PERMISOS DE GRANT Y CREATE USER EN EL SERVIDOR, ESTE USUARIO SOLO SERA UTILIZADO PARA EFECTOS DE INSTALACION YA QUE EL SISTEMA CREA 
SU PROPIO USUARIO
<BR><BR><BR>
CAMPO NUMERO 4 (CLAVE MYSQL): EN ESTE CAMPO DEVE INTRODUCIR LA CLAVE CORRESONDIENTE AL NOMBRE DE USUARIO DEL ANTERIOR CAMPO 
<BR><BR><BR>
CAMPO NUMERO 5 (HOST): EN ESTE CAMPO DEBERA INSERTAR HOST ASOCIADO AL USUARIO MYSQL POR DEFECTO ES LOCALHOST
<BR><BR><BR>
LOS SIGUIENTES 6 CAMPOS SON PARA CONFIGURAR EL PRIMER USUARIO DE SISTEMA ESTE USUARIO TENDRA PERMISO DE ADMINISTRADOR
CABE DESTACAR QUE EL USUARIO MYSQL Y ESTE SON DIFERENTES YA QUE EL DE MYSQL SE UTILIZARA PARA EFECTOS DE FUNCIONAMIENTO INTERNO Y EL USUARIO DE SISTEMA PARA EL ACCESO DESDE EL NAVEGADOR

</p><BR><BR><BR><br><br><br><br><br><br><br>
<P style="display: block;">
    UNA VEZ COMPLETADOS TODOS LOS CAMPOS SOLO HACE FALTA DAR CLICK EN EL BOTON (CONFIGURAR) Y EL SISTEMA EMPEZARA A CONFIGURARSE ESTO TARDARA UNOS SEGUNDOS 
    <BR> UNA VEZ CONFIGURADO APARECERA LA SIGUIENTE PAGINA SOLO DEVE INGRESAR SU NOMBRE DE USUARIO Y CONTRASEÑA E INGRESARA <br>
    <img src="img/ayuda/login.jpg" width="600" height="500" alt=""/>
</P>
<style>
   .list>li
   {
       list-style: circle;
       margin: 3px;
   }
    </style>
    <H1>POSIBLES PROBLEMAS AL INSTALAR</H1>
<h2>EN CASO DE QUE NO INSTALE Y SE MUESTRE ALGUN ERROR </h2>
<ul style="list-style: circle;" class="list">
    <li >VERIFIQUE QUE EL SERVIDOR MYSQL ESTA EN FUNCIONAMIENTO</li>
    <li>VERIFIQUE QUE EL NOMBRE DE USUARIO INSERTADO EN EL CAMPO (USUARIO MYSQL) ES CORRECTO Y SU CONTRASEÑA ES VALIDA </li>
</ul>
<BR><BR>
<h2>OLVIDO  EL NOMBRE DE USUARIO O LA CONTRASEÑA  QUE LE ASIGNO A SU USUARIO ADMINISTRADOR </h2>
SI ESTE ES EL CASO DIRIJASE A LA CAMPETA DONDE INSTALO EL SISTEMA LUEGO DIRIJASE AL DIRECTORIO protected/  ABRA EL ARCHIVO MysqlUser.php<BR> 
CON UN EDITOR DE TEXTO Y ELIMINE TODO SU CONTENIDO LUEGO RECARGE LA PAGINA LOGIN. ESTO LO LLEVARA DE NUEVO A LA PAGINA DE INSTALACION DONDE DEVERA REPETIR EN PROCESO
</div>