<?PHP
/**
 * @package CTEG
 * @subpackage VIEW
 */
?><?php

/* 
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */

?>
<DIV STYLE="MARGIN: 20PX; ">
  <H1><P ALIGN="CENTER">INGRESAR  UN TRABAJO ESPECIAL DE GRADO</P></H1>
  <P ALIGN="JUSTIFY"  >PARA INSERTAR UN TRABAJO DE ESPECIAL  DE GRADO DEBE DIRIGIR AL MENÚ T.E.G EL SUB MENÚ INSERTAR APARECERÁ LA SIGUIENTE  PANTALLA INSERTAR DATOS DEL
    TRABAJO ESPECIAL DE GRADO DONDE ENCONTRARAS  EL SIGUIENTE FORMULARIO AQUÍ ESCRIBIRÁS EL  TÍTULO DEL TRABAJO DE ESPECIAL DE GRADO SI  PRESIONAS EL BOTÓN VERIFICAR SE MOSTRARAN LOS TRABAJOS ESPECIALES DE GRADO QUE  TENGAN UN TÍTULO IGUAL O SIMILAR UNA VEZ VERIFICADO PRESIONA EL BOTÓN SIGUIENTE</P>
  <P ALIGN="JUSTIFY"> <IMG STYLE="" SRC="IMG/AYUDA/INSETAR TEG-1.JPG" WIDTH="408" HEIGHT="226"></P> 
  <P><BR> 
  LUEGO APARECERÁ LA SIGUIENTE PANTALLA </P>
  <P><IMG SRC="IMG/AYUDA/INSETAR TEG-2.JPG" WIDTH="515" HEIGHT="252"></P>
  <P ALIGN="JUSTIFY">EN ESTE FORMULARIO INSERTARAS LA CANTIDAD DE AUTORES QUE TIENE EL TRABAJO ESPECIAL DE GRADO LUEGO PRESIONA EL BOTÓN SIGUIENTE Y APARECERÁ EL SIGUIENTE FORMULARIO SI LOS AUTORES SON MÁS DE 1 APARECERÁ LA CANTIDAD CORRESPONDIENTE DE FORMULARIOS  </P>
  <P ALIGN="JUSTIFY"><IMG SRC="IMG/AYUDA/INSETAR TEG-3.JPG" WIDTH="464" HEIGHT="321"></P>
  <P><BR>
  <P ALIGN="JUSTIFY">UNA VEZ LLENADOS TODOS LOS CAMPOS DEBES PRESIONAR EL BOTÓN SIGUIENTE 
APARECERÁ LA EL SIGUIENTE FORMULARIO QUE CORRESPONDE A LOS DATOS DEL TUTOR 
</P>
  <P ALIGN="JUSTIFY"><IMG SRC="IMG/AYUDA/INSETAR TEG-4.JPG" WIDTH="409" HEIGHT="299"></P>
  <P ALIGN="JUSTIFY">UNA VEZ LLENADOS TODOS LOS CAMPOS PRESIONA EL BOTÓN SIGUIENTE
APARECERÁ LA SIGUIENTE PANTALLA <BR>
DONDE DEBERÁS INDICAR LA CANTIDAD DE JURADOS QUE CORRESPONDEN AL TRABAJO ESPECIAL DE GRADO
</P></P>
<IMG SRC="IMG/AYUDA/INSETAR TEG-5.JPG" WIDTH="505" HEIGHT="277">
<P>LUEGO PRESIONA ENVIAR  <BR>
HECHO ESTO APARECERÁN LOS FORMULARIOS CORRESPONDIENTES A  LOS JURADOS ANTES INDICADOS.</P>
<P><IMG SRC="IMG/AYUDA/INSETAR TEG-6.JPG" WIDTH="469" HEIGHT="330"></P>
<P>LLENA TODOS LOS CAMPOS Y PRESIONA GUARDAR
EN LA SIGUIENTE PANTALLA APARECERÁ UN FORMULARIO DONDE SE  DEBERÁ CARGAR UN ARCHIVO PDF, ESTE ARCHIVO DEBE CORRESPONDER AL TRABAJO ESPECIAL DE GRADO DIGITALIZADO
</P>
<P><IMG SRC=" IMG/AYUDA/INSETAR TEG-7.JPG" WIDTH="478" HEIGHT="247" STYLE="FLOAT:LEFT"> UNA VEZ SELECCIONADO EL ARCHIVO SE MOSTRARA AUTOMÁTICAMENTE UNA VISTA PREVIA DEL ARCHIVO PDF<BR><IMG SRC="IMG/AYUDA/INSETAR TEG-8.JPG" WIDTH="232" HEIGHT="230"></P>
<P>DESPUÉS PRESIONA EL BOTÓN GUARDAR 
LUEGO TE APARECERÁ LA SIGUIENTE PÁGINA DONDE INGRESARAS DATOS COMO LA CARRERA, EL PERIODO ACADÉMICO, MENCIÓN Y LAS OBSERVACIONES
</P>
<P><IMG SRC="IMG/AYUDA/INSETAR TEG-9.JPG" WIDTH="323" HEIGHT="296"></P>
<P>HECHO ESTO PRESIONAS EL BOTÓN SIGUIENTE Y APARECERÁ LA SIGUIENTE PANTALLA CON LA RECOPILACIÓN DE TODOS LOS DATOS INSERTADOS ANTERIORMENTE </P>
<P><IMG SRC="IMG/AYUDA/INSETAR TEG-10.JPG" WIDTH="439" HEIGHT="292"></P>

<P>UNA VEZ VERIFICADOS TODOS LOS DATOS PRESIONAS GUARDAR SI TODO SALE BIEN APARECERÁ LA SIGUIENTE PANTALLA </P>
<P><IMG SRC="IMG/AYUDA/INSETAR TEG-11.JPG" WIDTH="353" HEIGHT="290"></P>
</DIV>